apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: utils
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: talkz
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://github.com/the-one-rvs/talkz.git"
    targetRevision: main
    path: manifests/helm/utils
    helm:
      parameters: []
  destination:
    server: "https://kubernetes.default.svc"
    namespace: talkz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true