apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  labels:
    app: {{ .Values.svcName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
